<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.28" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Navi.ToolsAssets.Api/Navi.ToolsAssets.Api.csproj" />
    <ProjectReference Include="../../src/Navi.ToolsAssets.Application/Navi.ToolsAssets.Application.csproj" />
    <ProjectReference Include="../../src/Navi.ToolsAssets.Domain/Navi.ToolsAssets.Domain.csproj" />
    <ProjectReference Include="../../src/Navi.ToolsAssets.Shared/Navi.ToolsAssets.Shared.csproj" />
  </ItemGroup>

</Project>
